// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zfagpvlnlonfwtpmrfke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmYWdwdmxubG9uZnd0cG1yZmtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwODI2OTAsImV4cCI6MjA3MzY1ODY5MH0.IzzcwnNq1qk0Ht1V1xanllIGTnmcNmsTI5OCTwi4vSU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);